### PR TITLE
Fix contradiction in current language

### LINKED ISSUE #3: The result consistency provision is contradictory
## Description

Current proposal reads:

> `resultFor` MUST revert if the result for an `id` is not available yet. `resultFor` MUST return the same result for an `id` after that result is available.

However, short after, it explains that IDs are deterministically derived from an asset pair descriptor:

> `id`: Description of the required value. Should be standard between all providers. Proposition: use the keccak256 hash of a string describing the requested pair* 

It becomes apparent that both statements are in partial contradiction. If someone implemented business logic that strictly complied with the current language, it would be impossible to update the price point after it is initially set.

## Proposal

It comes to my mind that we have two alternative clear paths to follow from this point:
- Removing the consistency provision (`resultFor MUST return the same result for an `id` after that result is available.`)
- Advancing towards including a time reference inside the query ID so they are still predictably built but they are sensitive to time.

### PR DESCRIPTION
**Pull request by aesedepece**
This pull request:
- fixes existing contradiction in current language,
- builds on @Amxx 's suggestion about monotony,
- clarifies the origin of timestamps,
- paves the way for @themandalore et. al. to make a proposal about IDs,
- does minor edits to README styling and wording,
- updates and renames the interface so it complies with the latest specs, and
- upgrades the targeted compiler versions in the `pragma solidity` header of the interface.

Fix #3

### CODE REVIEW

**Comment by aesedepece** [comment]
When reviewing this pull request, this paragraph will quickly stand out:
> It is up to the implementor of an EIP-2362 compliant contract to set the associated timestamp to one of these:
>   - the timestamp of the block in which the returned value was last mutated (by invoking `block.timestamp` or `now()` at the updating transaction).
>   - an oracle-specific timestamp that offers a more precise metric of when the reported value was actually probed.

I wrote such thing because I don't really know if we are expecting one option, the other, or we simply prefer not to specify the origin of the timestamp. What do you think?

**Comment by aesedepece** [comment]
My main concern is that someone who is writing an medianizer contract may probably want to leave out the value coming from one of the EIP-2362 compliant contracts it is aggregating if the is too old or simply too far apart from the timestamps reported by other oracle contracts.

Under the expectation that such use case will exist for the standard interface, it becomes apparent to me that the EIP needs to be somehow explicit about what to expect from timestamps.

**Review by brendaloya — APPROVED** [review]

**Review by brendaloya — COMMENTED** [review]
Was the status code vetoed? My last recollection of this, is that we wanted to avoid reverting. So the status code was added to flag it so the user would be able to remove it from their aggregation or determine if it was unusable. We could do without the status code and if value is not found the timestamp could be set to 0 so the user can avoid it

**Comment by aesedepece** [comment]
The status code was removed in #2. Happy to discuss about recovering it back or specifying the `timestamp=0` thing.

**Comment by brendaloya** [comment]
> The status code was removed in #2. Happy to discuss about recovering it back or specifying the `timestamp=0` thing.

Yeah, we should talk about it. The last thing I remember is that reverting was the vetoed option but

**Pull request merged**
